fix: db and all the env

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -8,7 +8,7 @@ jobs:
   build:
     name: Build & Push Image
     runs-on: [self-hosted, backend]
-    environment: 'witzo-automation-development'
+    environment: 'konvoq-automation-development'
     defaults:
       run:
         working-directory: ${{ github.workspace }}
@@ -29,9 +29,9 @@ jobs:
           echo "Current dir: $(pwd)"
           ls -la
           if [ -f "Dockerfile" ]; then
-            echo "✓ Dockerfile found"
+            echo "âœ“ Dockerfile found"
           else
-            echo "✗ Dockerfile NOT found"
+            echo "âœ— Dockerfile NOT found"
             exit 1
           fi
 
@@ -39,17 +39,17 @@ jobs:
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build the Docker image
-        run: sudo docker build -t webomindapps1/witzo-automation-dev:latest .
+        run: sudo docker build -t webomindapps1/konvoq-automation-dev:latest .
 
       - name: Push to Docker Hub
-        run: sudo docker push webomindapps1/witzo-automation-dev:latest
+        run: sudo docker push webomindapps1/konvoq-automation-dev:latest
 
 
   deploy:
     name: Deploy to Self-Hosted
     needs: build
     runs-on: [self-hosted, backend]
-    environment: 'witzo-automation-development'
+    environment: 'konvoq-automation-development'
 
     steps:
       - name: Checkout code (so we have a workspace dir)
@@ -101,19 +101,20 @@ jobs:
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Pull Docker image
-        run: sudo docker pull webomindapps1/witzo-automation-dev:latest
+        run: sudo docker pull webomindapps1/konvoq-automation-dev:latest
 
       - name: Stop & remove old container (if any)
         run: |
-          docker stop cicd-pipeline-witzo-automation || true
-          docker rm   cicd-pipeline-witzo-automation || true
+          docker stop cicd-pipeline-konvoq-automation || true
+          docker rm   cicd-pipeline-konvoq-automation || true
 
       - name: Run Docker container
         run: |
           sudo docker run -d \
-            --name cicd-pipeline-witzo-automation \
+            --name cicd-pipeline-konvoq-automation \
             -p 8080:8080 \
             --restart always \
             -v /home/ubuntu/logsfiles:/logs \
             --env-file $GITHUB_WORKSPACE/.env \
-            webomindapps1/witzo-automation-dev:latest
+            webomindapps1/konvoq-automation-dev:latest
+
